version: "3"

services:
  rstudio:
    image: "anthesevenants/elastic-net-frequency:rstudio"
    ports: 
      - 8787:8787
      - 8788:8788
    environment:
      DISABLE_AUTH: true
    volumes:
      - .:/home/rstudio/elastic-net-frequency/:Z
